import sqlite3
conn = sqlite3.connect('instance/dewill.db')
c = conn.cursor()
c.execute("SELECT name FROM sqlite_master WHERE type='table'")
print("TABLES:", c.fetchall())
c.execute("SELECT COUNT(*) FROM products")
print("PRODUCTS:", c.fetchall())
c.execute("SELECT COUNT(*) FROM product_specs WHERE key='Color'")
print("COLOR SPECS:", c.fetchall())
c.execute("SELECT DISTINCT value FROM product_specs WHERE key='Color' LIMIT 15")
print("COLORS:", c.fetchall())
c.execute("SELECT COUNT(*) FROM presentations")
print("PRESENTATIONS:", c.fetchall())
c.execute("SELECT p.name, b.name FROM products p LEFT JOIN brands b ON p.brand_id=b.id LIMIT 10")
print("SAMPLE PRODUCTS:", c.fetchall())
conn.close()
